import yfinance as yf
import pandas as pd
import math
import os
import time

# --- CONFIGURATION ---
# Swapped TATAMOTORS.NS -> MARUTI.NS to fix the 404 Error
STOCKS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "TATASTEEL.NS",
    "COALINDIA.NS", "MARUTI.NS", "SUNPHARMA.NS", "ONGC.NS", "POWERGRID.NS",
    "NTPC.NS", "M&M.NS", "TITAN.NS", "BAJFINANCE.NS", "WIPRO.NS"
]

results = []

print(f"🚀 STARTING DASHBOARD GENERATION ({len(STOCKS)} Stocks)...")
print("-" * 60)

for symbol in STOCKS:
    try:
        # 1. FETCH DATA 
        stock = yf.Ticker(symbol)
        info = stock.info
        
        price = info.get('currentPrice', 0)
        book_value = info.get('bookValue', 0)
        eps = info.get('trailingEps', 0)
        pe_ratio = info.get('trailingPE', 0)
        dividend = info.get('dividendYield', 0)
        
        # Handle None values safely
        if dividend is None: dividend = 0
        else: dividend = dividend * 100
        
        # Skip garbage data
        if book_value <= 0 or eps <= 0:
            print(f"Skipping {symbol} (Incomplete Data)")
            continue

        # 2. GRAHAM NUMBER (Fair Value)
        graham_value = math.sqrt(22.5 * eps * book_value)
        
        # 3. MARGIN OF SAFETY
        margin_of_safety = ((graham_value - price) / graham_value) * 100
        
        # 4. VERDICT ENGINE
        verdict = "HOLD"
        color = "#6c757d" # Gray
        
        if price < graham_value:
            verdict = "💎 STRONG BUY"
            color = "#28a745" # Green
        elif price < graham_value * 1.2:
            verdict = "✅ FAIR VALUE"
            color = "#17a2b8" # Blue
        else:
            verdict = "❌ OVERPRICED"
            color = "#dc3545" # Red
            
        print(f"Analyzed {symbol}...")

        results.append({
            "Stock": symbol,
            "Price": round(price, 2),
            "Fair Value": round(graham_value, 2),
            "Safety": round(margin_of_safety, 1),
            "PE": round(pe_ratio, 2),
            "Div Yield": round(dividend, 2),
            "Verdict": verdict,
            "Color": color
        })
            
    except Exception as e:
        print(f"⚠️ Error with {symbol}: {e}")

# --- HTML DASHBOARD GENERATOR ---
html_content = f"""
<html>
<head>
    <title>Institutional Valuation Dashboard</title>
    <style>
        body {{ font-family: 'Segoe UI', sans-serif; background-color: #f4f4f9; padding: 20px; }}
        h1 {{ text-align: center; color: #333; }}
        .card {{ background: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.1); max-width: 1000px; margin: auto; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #007bff; color: white; }}
        tr:hover {{ background-color: #f1f1f1; }}
        .badge {{ padding: 5px 10px; border-radius: 5px; color: white; font-weight: bold; font-size: 0.9em; }}
    </style>
</head>
<body>
    <div class="card">
        <h1>📊 Algo-generated Valuation Report</h1>
        <p>Generated by Python | Strategy: Benjamin Graham Intrinsic Value</p>
        <table>
            <thead>
                <tr>
                    <th>Stock</th>
                    <th>Price</th>
                    <th>Fair Value</th>
                    <th>Margin of Safety</th>
                    <th>P/E</th>
                    <th>Div Yield</th>
                    <th>Verdict</th>
                </tr>
            </thead>
            <tbody>
"""

# Add rows sorted by Safety
for row in sorted(results, key=lambda x: x['Safety'], reverse=True):
    html_content += f"""
                <tr>
                    <td><b>{row['Stock']}</b></td>
                    <td>₹{row['Price']}</td>
                    <td>₹{row['Fair Value']}</td>
                    <td style="color: {'green' if row['Safety'] > 0 else 'red'}"><b>{row['Safety']}%</b></td>
                    <td>{row['PE']}</td>
                    <td>{row['Div Yield']}%</td>
                    <td><span class="badge" style="background-color: {row['Color']}">{row['Verdict']}</span></td>
                </tr>
    """

html_content += """
            </tbody>
        </table>
    </div>
</body>
</html>
"""

filename = "dashboard.html"
with open(filename, "w", encoding="utf-8") as f:
    f.write(html_content)

print("\n" + "="*60)
print("✅ DASHBOARD GENERATED!")
print("📂 Opening in your browser now...")
os.startfile(filename)